### ISSUE TITLE
Mejorar cabecera

### ISSUE THREAD

**Issue by oscarperpinan** [cjgb/sitio7jr#5]
Opciones:
- Disminuir contraste o aumentar transparencia de la foto
- Cambiar color del texto

**Comment by maritrinez** [comment]
¿creéis que aún no se ve bien? lo mejoré el otro día

**Comment by oscarperpinan** [comment]
Perdón, fallo mío. Estaba viendo una versión anterior.

**Comment by oscarperpinan** [comment]
https://github.com/cjgb/sitio7jr/commit/cf1d0bce802cbd02ccbdcc8f161ce2cad5ace60a
