### ISSUE TITLE
Añadir flecha de desplazamiento vertical en todas las secciones

### ISSUE THREAD

**Issue by oscarperpinan** [cjgb/sitio7jr#8]
En la portada aparece una flecha que permite el desplazamiento vertical a la sección "Presentación", pero en el resto de las secciones no.

**Comment by cjgb** [comment]
Creo que lo tengo en la nueva version. No sé si hay que cambiar el color de las flechas. Además, el CSS metido a pelo en el html me horroriza. ¿Mejor pasarlo a custom.css?

**Comment by oscarperpinan** [comment]
He modificado la posición de una flecha (estaba en el div que no le correspondía) y también su color.
Es verdad que estaría bien añadir el color a custom.css, pero hay dos tipos de color, según si tienen de fondo una foto o no.
