### ISSUE TITLE
Reordenar personas de los comités por orden alfabético

### ISSUE THREAD

**Issue by oscarperpinan** [cjgb/sitio7jr#9]

**Comment by cjgb** [comment]
¿De nombre o de apellido? ¡Uno de los motivos por los que no quise ordenar alfabéticamente por nombre es que aparecía yo el primero!

**Comment by oscarperpinan** [comment]
Jeje, aún así yo ordenaría por apellido.

**Comment by oscarperpinan** [comment]
https://github.com/cjgb/sitio7jr/commit/fda9f615afff7806c03eb5ffe2158b13d76545f8
